#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Wrong number of inputs. Instead use: $0 WHERE NAME "
    exit 1
fi

#Use the search script to find files 
#^then sum their sizes
total_size=0
while read -r file; do
    file_size=$(wc -c < "$file")
    total_size=$((total_size + file_size))
done < <(./search "$1" "$2")

echo "$total_size"

